spring:
    datasource:
        password: y686ah178
        url: jdbc:postgresql://localhost:5432/sales_db_2
        username: listenexorcist
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    thymeleaf:
        cache: false
        enabled: true
        prefix: classpath:/templates/
        suffix: .html